# -*- coding: utf-8 -*-
"""TransformerMediTextSimplification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mOl5lG-zOIlbIkwp6tjTofVrBUfwBnxh
"""

!pip install transformers torch rouge-score nltk

# ===============================================
# Medical Text Simplification using BART
# ===============================================

# 1. Install Required Libraries
# Run this once in Colab
# !pip install transformers torch rouge-score nltk

# ===============================================
# 2. Import Libraries
# ===============================================

import torch
import re
from transformers import BartTokenizer, BartForConditionalGeneration
from rouge_score import rouge_scorer


# ===============================================
# 3. Load Pretrained BART Model
# ===============================================

model_name = "facebook/bart-large"

tokenizer = BartTokenizer.from_pretrained(model_name)
model = BartForConditionalGeneration.from_pretrained(model_name)


# ===============================================
# 4. Medical Dictionary for Simplification
# ===============================================

medical_dictionary = {

    "hypertension": "high blood pressure",
    "hyperglycemia": "high blood sugar",
    "myocardial infarction": "heart attack",
    "dyspnea": "shortness of breath",
    "analgesic": "pain reliever",
    "edema": "swelling",
    "tachycardia": "fast heart rate",
    "bradycardia": "slow heart rate",
    "intravenous": "given through a vein",
    "antibiotic": "medicine that fights infection"
}


# ===============================================
# 5. Preprocessing Function
# ===============================================

def preprocess_text(text):

    text = text.lower()
    text = re.sub(r'\s+', ' ', text)
    text = text.strip()

    return text


# ===============================================
# 6. Medical Term Replacement
# ===============================================

def replace_medical_terms(text):

    for term in medical_dictionary:
        text = text.replace(term, medical_dictionary[term])

    return text


# ===============================================
# 7. BART Simplification Function
# ===============================================

def simplify_medical_text(text):

    text = preprocess_text(text)

    prompt = """
Rewrite the following medical text in simple language that a patient can understand.
Explain medical terms clearly.

Text:
""" + text

    inputs = tokenizer(prompt, return_tensors="pt", max_length=512, truncation=True)

    outputs = model.generate(
        inputs["input_ids"],
        max_length=150,
        min_length=40,
        num_beams=5,
        temperature=0.9,
        no_repeat_ngram_size=3,
        early_stopping=True
    )

    simplified_text = tokenizer.decode(outputs[0], skip_special_tokens=True)

    simplified_text = replace_medical_terms(simplified_text)

    return simplified_text


# ===============================================
# 8. Evaluation Function (ROUGE Score)
# ===============================================

def evaluate(original, simplified):

    scorer = rouge_scorer.RougeScorer(['rouge1', 'rougeL'], use_stemmer=True)

    scores = scorer.score(original, simplified)

    return scores


# ===============================================
# 9. Example Medical Texts
# ===============================================

medical_texts = [

    "The patient presents with hypertension and hyperglycemia requiring antihypertensive therapy.",

    "The patient suffered an acute myocardial infarction and requires immediate medical attention.",

    "Dyspnea and tachycardia were observed during physical examination.",

    "Intravenous antibiotics were administered to treat bacterial infection."
]


# ===============================================
# 10. Run Simplification
# ===============================================

for text in medical_texts:

    simplified = simplify_medical_text(text)

    print("\n--------------------------------------")
    print("Original Text:\n", text)
    print("\nSimplified Text:\n", simplified)

    scores = evaluate(text, simplified)

    print("\nROUGE Score:\n", scores)


# ===============================================
# 11. Custom User Input
# ===============================================

while True:

    user_input = input("\nEnter medical text (or type 'exit'): ")

    if user_input.lower() == "exit":
        break

    simplified = simplify_medical_text(user_input)

    print("\nSimplified Output:\n", simplified)